[package]
name = "bmp390-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal-async = { version = "1.0.0", optional = true}
embedded-hal = {version = "1.0.0", optional = true}
async-trait = "0.1.89"

[features]
default = ["async"]
async = ["dep:embedded-hal-async"]
sync = ["dep:embedded-hal"]